# permissions for end users to edit releases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elemental-lifecycle-manager
    app.kubernetes.io/managed-by: kustomize
  name: release-editor-role
rules:
- apiGroups:
  - lifecycle.suse.com
  resources:
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.suse.com
  resources:
  - releases/status
  verbs:
  - get
